name: CI

on: [push, pull_request]

jobs:
    ci:
        name: Lint and Format Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: 20.x

            - name: Install Deps
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Run Prettier
              run: npm run format:check
